name: kiddin9_openwrt
services:
  kiddin9_openwrt:
    volumes:
      - "/:/mnt/host"
      - "./root/etc/config/dhcp:/etc/config/dhcp"
      - "./root/etc/shadow:/etc/shadow"
      - "./root/etc/shadow-:/etc/shadow-"
      - "./root/etc/config/firewall:/etc/config/firewall"
      - "./root/etc/config/network:/etc/config/network"
    restart: always
    container_name: kiddin9_openwrt

    environment:
      - "TZ=Asia/Shanghai"
    stdin_open: true

    tty: true
    privileged: true
    networks:
      app_net:
        ipv6_address: fc00:1111:1111:1111::2
        ipv4_address: 172.20.254.2
    image: kiddin9_openwrt
    command: /sbin/init
    ports:
      - "58000:80"
networks:
  app_net:
    driver: bridge

    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.254.0/24

        - subnet: fc00:1111:1111:1111::/64
